language: elixir
elixir: 1.6
notifications:
  recipients:
    - yevhenii@libraventur.es
otp_release:
  - 20.0
script:
  - "MIX_ENV=test mix do deps.get, test && mix compile && MIX_ENV=test mix coveralls.travis"
